# @brief   ptp Makefile for Unix like environment.
# @author  eel3
# @date    2014/10/27
#
# @note
# - GCC 4.1.2 on CentOS 5 64bit

app        := ptp
CFLAGS     := -Wall -ansi -pedantic
LDLIBS     := 

.PHONY: all
all: $(app)

.PHONY: clean
clean:
	$(RM) $(app)
