# @brief   ptp Makefile for Visual C++ and NMAKE.
# @author  eel3
# @date    2014/10/27
#
# @note
# - Visual Studio 2005 Professional SP1
# - Visual Studio 2010 Professional SP1

app         = ptp
CFLAGS      = /GS /W4 /MT /D_CONSOLE /D_UNICODE /DUNICODE /DWIN32

all: $(app).exe

clean:
	del $(app).exe $(app).obj
